"use client"

import { useEffect, useState } from "react"
import Head from "next/head"
import { Geist, Geist_Mono } from "next/font/google"
import Navbar from "@/components/navbar"
import Image from "next/image"
import ButtonBlue from "@/components/button_blue"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export default function RootLayout({
  children,
  metaTitle,
}: {
  children: React.ReactNode
  metaTitle?: string
}) {
  const [isBlur, setIsBlur] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setIsBlur(window.scrollY > 50) // aktif blur kalau sudah scroll > 50px
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])

  return (
    <>
      <Head>
        <title>{`Pharmago - ${metaTitle || ""}`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <div className="min-h-screen w-full flex flex-col bg-gradient-to-b from-sky-100 to-blue-100 "> */}
        <div className="min-h-screen w-full flex flex-col bg-gradient-to-b from-[#E1ECF7] via-[#F0F8FF] via-[#F8F9FB] to-[#FFFFFF]">

        {/* ✅ Header (Logo - Navbar - Search) */}
        <header
          className={`sticky top-0 z-50 transition-all duration-300 ${
            isBlur ? "backdrop-blur-md bg-white/50 shadow-sm" : ""
          }`}
        >
          <div className="flex items-center justify-between w-full px-10 py-6">
            {/* Logo kiri */}
            <Image
              src="/logo.png"
              alt="Pharmago Logo"
              width={200}
              height={200}
              className="object-contain"
            />

            {/* Navbar di tengah */}
            <div className="flex-1 flex justify-center">
              <Navbar />
            </div>

            {/* Button kanan */}
            <ButtonBlue>Search</ButtonBlue>
          </div>
        </header>

        {/* Main Content */}
        <main className="flex-1 px-10">{children}</main>
      </div>
    </>
  )
}
